## Imports

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
tf.__version__

'2.12.0'

## Preprocessing



### Load dataset

In [ ]:
from sklearn.datasets import load_digits
digits = load_digits()

X = digits.data  # we only take the first two features.
y = digits.target

print('X.shape:', X.shape)
print('y.shape:', y.shape)

print(X[0:5,:])
print(y[0:20])

X.shape: (1797, 64)
y.shape: (1797,)
[[ 0.  0.  5. 13.  9.  1.  0.  0.  0.  0. 13. 15. 10. 15.  5.  0.  0.  3.
  15.  2.  0. 11.  8.  0.  0.  4. 12.  0.  0.  8.  8.  0.  0.  5.  8.  0.
   0.  9.  8.  0.  0.  4. 11.  0.  1. 12.  7.  0.  0.  2. 14.  5. 10. 12.
   0.  0.  0.  0.  6. 13. 10.  0.  0.  0.]
 [ 0.  0.  0. 12. 13.  5.  0.  0.  0.  0.  0. 11. 16.  9.  0.  0.  0.  0.
   3. 15. 16.  6.  0.  0.  0.  7. 15. 16. 16.  2.  0.  0.  0.  0.  1. 16.
  16.  3.  0.  0.  0.  0.  1. 16. 16.  6.  0.  0.  0.  0.  1. 16. 16.  6.
   0.  0.  0.  0.  0. 11. 16. 10.  0.  0.]
 [ 0.  0.  0.  4. 15. 12.  0.  0.  0.  0.  3. 16. 15. 14.  0.  0.  0.  0.
   8. 13.  8. 16.  0.  0.  0.  0.  1.  6. 15. 11.  0.  0.  0.  1.  8. 13.
  15.  1.  0.  0.  0.  9. 16. 16.  5.  0.  0.  0.  0.  3. 13. 16. 16. 11.
   5.  0.  0.  0.  0.  3. 11. 16.  9.  0.]
 [ 0.  0.  7. 15. 13.  1.  0.  0.  0.  8. 13.  6. 15.  4.  0.  0.  0.  2.
   1. 13. 13.  0.  0.  0.  0.  0.  2. 15. 11.  1.  0.  0.  0.  0.  0.  1.
  12. 12.  1.  0.  0

### Cross validation

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=123)

print('X_train.shape', X_train.shape)
print('y_train.shape', y_train.shape)
print('X_test.shape', X_test.shape)
print('y_test.shape', y_test.shape)

X_train.shape (1078, 64)
y_train.shape (1078,)
X_test.shape (719, 64)
y_test.shape (719,)


### Data normalization



In [ ]:
X_train = X_train /16
X_test = X_test /16

print(X_train[0:5,:])

[[0.     0.     0.     0.8125 0.75   0.     0.     0.     0.     0.
  0.     0.875  1.     0.0625 0.     0.     0.     0.     0.0625 0.9375
  1.     0.0625 0.     0.     0.     0.     0.25   1.     1.     0.1875
  0.     0.     0.     0.     0.3125 0.9375 1.     0.5625 0.     0.
  0.     0.     0.     0.     0.75   0.9375 0.0625 0.     0.     0.
  0.0625 0.6875 0.5625 1.     0.6875 0.125  0.     0.     0.     0.6875
  1.     1.     1.     1.    ]
 [0.     0.     0.625  0.625  0.75   0.4375 0.     0.     0.     0.
  0.9375 0.8125 0.3125 0.75   0.3125 0.     0.     0.25   0.8125 0.25
  0.     0.125  0.5    0.     0.     0.5    0.25   0.     0.     0.1875
  0.5    0.     0.     0.5    0.25   0.     0.     0.4375 0.3125 0.
  0.     0.375  0.375  0.     0.     0.6875 0.125  0.     0.     0.0625
  0.8125 0.1875 0.1875 0.75   0.     0.     0.     0.     0.4375 0.9375
  1.     0.4375 0.     0.    ]
 [0.     0.     0.     0.125  0.9375 0.5    0.     0.     0.     0.
  0.     0.6875 1.     0.25 

## Learning

### Creating the Adaline

In [ ]:
from keras.activations import linear
X_input = tf.keras.layers.Input([64])
y_pred = tf.keras.layers.Dense(units=10, activation='sigmoid', kernel_initializer='zeros')(X_input)

model = tf.keras.models.Model(inputs=X_input, outputs=y_pred)

model.compile(loss='sparse_categorical_crossentropy', metrics='accuracy', optimizer=tf.keras.optimizers.SGD(learning_rate=0.05))

model.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 64)]              0         
                                                                 
 dense_2 (Dense)             (None, 10)                650       
                                                                 
Total params: 650
Trainable params: 650
Non-trainable params: 0
_________________________________________________________________


### Train

In [ ]:
model.fit(X_train, y_train, epochs=10, batch_size=5, verbose=1)

Epoch 1/10
216/216 [==============================] - 2s 7ms/step - loss: 1.6047 - accuracy: 0.6939
Epoch 2/10
216/216 [==============================] - 3s 12ms/step - loss: 0.8687 - accuracy: 0.8915
Epoch 3/10
216/216 [==============================] - 1s 3ms/step - loss: 0.6145 - accuracy: 0.9137
Epoch 4/10
216/216 [==============================] - 0s 2ms/step - loss: 0.4916 - accuracy: 0.9286
Epoch 5/10
216/216 [==============================] - 2s 8ms/step - loss: 0.4173 - accuracy: 0.9341
Epoch 6/10
216/216 [==============================] - 1s 5ms/step - loss: 0.3688 - accuracy: 0.9351
Epoch 7/10
216/216 [==============================] - 1s 2ms/step - loss: 0.3360 - accuracy: 0.9425
Epoch 8/10
216/216 [==============================] - 2s 11ms/step - loss: 0.3090 - accuracy: 0.9416
Epoch 9/10
216/216 [==============================] - 1s 2ms/step - loss: 0.2881 - accuracy: 0.9471
Epoch 10/10
216/216 [==============================] - 1s 4ms/step - loss: 0.2720 - accuracy: 0.95

## Evaluation

In [ ]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)

23/23 [==============================] - 0s 7ms/step - loss: 0.2858 - accuracy: 0.9402


In [ ]:
y_test_pred = model.predict(X_test)

print(y_test_pred)

23/23 [==============================] - 0s 1ms/step
[[0.33106855 0.1449729  0.79227555 ... 0.53120524 0.4695071  0.95290816]
 [0.44688195 0.21875896 0.5809195  ... 0.42727804 0.5672329  0.95036507]
 [0.26135206 0.80636454 0.06496188 ... 0.65934235 0.3919782  0.22838578]
 ...
 [0.10238575 0.37692204 0.65138996 ... 0.27875465 0.668335   0.8884785 ]
 [0.53461283 0.7572476  0.08039778 ... 0.49889404 0.3348434  0.24991325]
 [0.24798548 0.22639097 0.78436244 ... 0.12772113 0.9375457  0.87274915]]


In [ ]:
y_test_pred = np.argmax(y_test_pred, axis=1)

print(y_test_pred)

[3 3 4 4 1 3 1 0 7 4 0 0 5 1 6 0 3 1 0 6 9 7 7 5 4 4 7 0 0 9 1 6 8 6 1 4 6
 2 1 6 0 6 2 0 2 3 0 8 8 1 2 8 6 5 1 6 4 6 0 4 3 5 6 2 6 8 1 2 0 1 7 9 4 7
 8 9 4 3 3 1 9 5 4 6 1 2 4 2 4 5 8 4 1 7 6 7 5 5 1 3 9 4 6 6 8 1 7 9 6 4 9
 8 7 0 9 0 2 9 0 5 1 4 4 2 2 0 7 3 6 8 2 5 2 3 3 9 6 7 4 0 7 3 2 2 2 3 8 1
 7 1 5 7 9 1 3 8 6 0 7 9 6 0 2 6 3 1 5 5 9 6 1 8 6 1 1 4 4 2 0 5 9 0 7 0 7
 5 8 4 8 8 3 7 9 8 2 0 3 4 9 4 1 8 7 0 5 4 5 7 2 1 4 2 0 8 7 3 2 9 2 3 8 0
 6 0 2 8 7 5 4 8 0 1 5 5 0 9 9 7 7 1 4 2 4 7 1 3 0 8 2 8 6 6 3 5 6 4 5 4 6
 5 7 7 9 9 1 0 4 6 1 7 3 9 8 1 0 4 9 0 8 2 5 8 4 0 8 3 1 6 6 4 6 1 4 6 6 4
 9 5 3 0 1 6 0 2 5 5 8 8 2 6 0 1 9 5 1 6 9 2 8 2 4 9 8 7 3 3 2 4 0 9 4 3 6
 0 2 1 3 3 2 5 9 0 7 5 9 7 6 4 7 9 6 7 4 1 5 9 6 5 5 0 8 9 3 2 7 8 7 5 7 1
 8 7 5 5 8 4 6 0 0 8 3 0 9 2 9 1 0 0 6 9 0 7 1 4 7 1 0 4 1 4 1 0 2 5 4 2 3
 9 7 0 6 7 5 0 8 5 3 4 7 6 4 1 4 3 3 9 4 3 9 6 0 3 7 9 9 8 9 9 1 9 5 7 8 6
 9 1 0 5 5 9 7 3 1 8 7 7 2 8 0 2 5 0 2 4 6 9 4 0 1 7 5 2 1 0 9 1 9 3 2 3 8
 7 0 2 1 1 7 7 1 6 3 5 7 

In [ ]:
print(y_test)

[3 3 4 4 1 3 1 0 7 4 0 0 5 1 6 0 3 1 0 6 9 7 7 5 4 5 7 0 0 9 1 6 8 6 8 4 6
 2 1 6 0 6 2 0 2 3 5 8 8 8 2 8 6 5 1 6 4 6 0 4 3 5 6 2 8 8 8 2 0 1 7 9 4 7
 3 9 4 3 3 8 9 5 4 6 1 2 4 2 4 5 8 4 1 7 6 7 5 5 6 3 9 4 6 6 8 1 7 5 6 4 9
 8 7 0 9 0 2 9 0 5 1 4 4 2 2 0 7 3 6 8 2 5 2 3 3 9 6 7 4 0 7 3 2 2 2 3 8 1
 7 1 5 7 9 1 3 2 6 0 7 9 6 0 2 6 3 1 5 5 9 6 1 8 6 1 3 4 4 2 0 5 9 0 7 0 7
 5 8 4 8 8 3 7 9 8 2 0 3 4 9 4 8 8 7 0 5 4 5 2 2 1 4 2 0 8 7 3 2 9 2 3 8 0
 6 0 2 8 7 5 4 8 0 1 5 5 0 9 8 7 7 1 4 2 4 7 1 3 0 8 2 8 6 6 3 5 6 4 5 4 6
 5 7 7 9 9 1 0 4 6 1 4 3 9 8 1 0 4 5 6 8 2 5 8 4 0 8 3 1 6 6 4 6 1 4 6 6 4
 1 5 3 0 1 6 0 2 5 5 8 8 2 6 0 1 1 5 1 6 9 2 8 2 4 9 8 3 3 3 2 4 0 9 4 3 6
 0 2 1 3 3 2 5 9 0 7 5 9 7 6 4 7 9 6 7 4 1 5 9 6 5 5 0 8 9 3 2 7 9 7 5 7 9
 8 7 5 5 8 4 1 0 0 8 3 0 9 2 9 1 0 0 6 9 0 7 1 4 7 1 0 4 1 4 8 0 2 5 4 2 3
 9 7 0 6 7 5 0 8 5 3 4 2 6 4 1 4 3 9 8 4 3 5 6 0 3 7 5 9 4 9 9 1 9 5 7 8 6
 9 1 0 5 5 9 7 3 1 8 7 7 2 9 0 2 5 0 2 4 6 1 4 0 1 7 5 2 1 0 9 1 9 3 2 3 8
 7 0 2 1 1 9 7 1 6 3 5 7 

In [ ]:
np.sum(y_test==y_test_pred) / np.size(y_test)

0.9401947148817803