## Imports

In [0]:
import numpy as np
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

## Preprocessing



### Load dataset

In [10]:
from sklearn.datasets import load_iris

data = load_iris()
X, y = data.data, data.target

print('Class label counts:', np.bincount(y))
print('X.shape:', X.shape)
print('y.shape:', y.shape)

print(X[0])
print(y[0])

Class label counts: [50 50 50]
X.shape: (150, 4)
y.shape: (150,)
[5.1 3.5 1.4 0.2]
0


One Hot encoding



In [11]:
from keras.utils import to_categorical

y = to_categorical(y)
print(y[0])
print(y[50])
print(y[100])

[1. 0. 0.]
[0. 1. 0.]
[0. 0. 1.]


### Cross validation

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=123)

print('X_train.shape', X_train.shape)
print('y_train.shape', y_train.shape)
print('X_test.shape', X_test.shape)
print('y_test.shape', y_test.shape)

X_train.shape (90, 4)
y_train.shape (90, 3)
X_test.shape (60, 4)
y_test.shape (60, 3)


### Data normalization



In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

print('X_train mean', np.mean(X_train))
print('X_train standard deviation', np.std(X_train))

X_train mean 7.031412489292658e-16
X_train standard deviation 0.9999999999999999


## Learning

### Creating the Logistic Regression

In [15]:
model = tf.keras.models.Sequential()
model.add(tf.keras.Input(shape=(4,)))
model.add(tf.keras.layers.Dense(3, kernel_initializer='zeros'))
model.add(tf.keras.layers.Activation('sigmoid')) 

model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['categorical_accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 15        
_________________________________________________________________
activation (Activation)      (None, 3)                 0         
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


### Train

In [16]:
model.fit(X_train, y_train, epochs=10, batch_size=5, verbose=1)

Epoch 1/10
18/18 [==============================] - 0s 2ms/step - loss: 1.0807 - categorical_accuracy: 0.7222
Epoch 2/10
18/18 [==============================] - 0s 2ms/step - loss: 1.0444 - categorical_accuracy: 0.7889
Epoch 3/10
18/18 [==============================] - 0s 2ms/step - loss: 1.0121 - categorical_accuracy: 0.7889
Epoch 4/10
18/18 [==============================] - 0s 2ms/step - loss: 0.9832 - categorical_accuracy: 0.7889
Epoch 5/10
18/18 [==============================] - 0s 3ms/step - loss: 0.9572 - categorical_accuracy: 0.8000
Epoch 6/10
18/18 [==============================] - 0s 2ms/step - loss: 0.9335 - categorical_accuracy: 0.8111
Epoch 7/10
18/18 [==============================] - 0s 2ms/step - loss: 0.9121 - categorical_accuracy: 0.8111
Epoch 8/10
18/18 [==============================] - 0s 2ms/step - loss: 0.8925 - categorical_accuracy: 0.8111
Epoch 9/10
18/18 [==============================] - 0s 2ms/step - loss: 0.8742 - categorical_accuracy: 0.8111
Epoch 10/1

## Evaluation

In [17]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 3ms/step - loss: 0.8143 - categorical_accuracy: 0.9000


In [18]:
y_test_pred = model.predict(X_test)
print(y_test_pred)

[[0.3293402  0.5878786  0.59107655]
 [0.2811191  0.5665134  0.667009  ]
 [0.27427977 0.5841164  0.6625661 ]
 [0.47397882 0.51378345 0.48593688]
 [0.77115005 0.38358045 0.2522648 ]
 [0.37639356 0.5396902  0.57534176]
 [0.3437562  0.59660435 0.56607467]
 [0.7597013  0.41625842 0.24483542]
 [0.7316451  0.44709498 0.25618938]
 [0.43416145 0.55404574 0.4970945 ]
 [0.2827148  0.5572213  0.6720527 ]
 [0.7829286  0.3378891  0.2690035 ]
 [0.4663957  0.53781897 0.47489253]
 [0.3209709  0.555771   0.6271477 ]
 [0.20634659 0.59088    0.7433206 ]
 [0.28022605 0.56844836 0.66698796]
 [0.72915864 0.40206242 0.28842735]
 [0.7609594  0.42974088 0.2350819 ]
 [0.39811245 0.54088074 0.54886043]
 [0.71176475 0.44492647 0.27896672]
 [0.73307276 0.40895277 0.27933943]
 [0.3518716  0.5610096  0.5861229 ]
 [0.7383173  0.40988892 0.27301422]
 [0.36646578 0.5423914  0.58458084]
 [0.76517975 0.3719153  0.267274  ]
 [0.7128603  0.41549978 0.29764354]
 [0.70432174 0.41728017 0.30620098]
 [0.35995436 0.55973303 0.57

In [19]:
print(model.get_weights()[0])
print(model.get_weights()[1])

[[-0.21551709  0.04544187  0.19904298]
 [ 0.18186337 -0.16578679 -0.06487003]
 [-0.2763915   0.09150375  0.23186293]
 [-0.267023    0.06517315  0.245585  ]]
[-0.08262867  0.02675044 -0.05810794]
